[start]
bind = "127.0.0.1:8000"
log = "info"
user = "testuser"
pass = "testpass"
allow-all = true
allow-funcs = true

[storage]
storage = "rocksdb"

[env]
SURREAL_BUILD_METADATA = false
SURREAL_COUNT_BATCH_SIZE = 10000
SURREAL_EXPERIMENTAL_BEARER_ACCESS = false
SURREAL_EXPORT_BATCH_SIZE = 1000
SURREAL_EXTERNAL_SORTING_BUFFER_LIMIT = 50000
SURREAL_FUNCTION_ALLOCATION_LIMIT = 20
SURREAL_EXPERIMENTAL_GRAPHQL =  false
SURREAL_HTTP_MAX_ML_BODY_SIZE = 4398046511104 
SURREAL_HTTP_MAX_SQL_BODY_SIZE = 1048576 
SURREAL_HTTP_MAX_RPC_BODY_SIZE = 4194304 
SURREAL_HTTP_MAX_KEY_BODY_SIZE = 16384 
SURREAL_HTTP_MAX_SIGNUP_BODY_SIZE = 1024 
SURREAL_HTTP_MAX_SIGNIN_BODY_SIZE = 1024 
SURREAL_HTTP_MAX_IMPORT_BODY_SIZE = 4398046511104 
SURREAL_IMPORT_FILE = "None"
SURREAL_INSECURE_FORWARD_ACCESS_ERRORS = false
SURREAL_MAX_CONCURRENT_TASKS = 64
SURREAL_MAX_OBJECT_PARSING_DEPTH = 10
SURREAL_MAX_QUERY_PARSING_DEPTH = 20
SURREAL_MAX_STREAM_BATCH_SIZE = 1000
SURREAL_NORMAL_FETCH_SIZE = 50
SURREAL_NET_MAX_CONCURRENT_REQUESTS = 1048576
SURREAL_RUNTIME_MAX_BLOCKING_THREADS = 512
SURREAL_RUNTIME_STACK_SIZE = 10485760 
SURREAL_SCRIPTING_MAX_MEMORY_LIMIT = 2097152 
SURREAL_SCRIPTING_MAX_STACK_SIZE = 262144 
SURREAL_TELEMETRY_DISABLE_TRACING =  false
SURREAL_TELEMETRY_DISABLE_METRICS =  false
SURREAL_TELEMETRY_NAMESPACE = "None"
SURREAL_TELEMETRY_PROVIDER = "None"
SURREAL_TEMPORARY_DIRECTORY = "None"
SURREAL_TRANSACTION_CACHE_SIZE = 10000
SURREAL_WEBSOCKET_MAX_FRAME_SIZE = 16777216 
SURREAL_WEBSOCKET_MAX_MESSAGE_SIZE = 134217728 
SURREAL_WEBSOCKET_RESPONSE_BUFFER_SIZE = 100
SURREAL_WEBSOCKET_RESPONSE_CHANNEL_SIZE = 100


